server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka



zuul:
  ignoredServices: '*'
  routes:
    customer:
      serviceId: customer-service
      path: /api-customer/**