language: java
jdk:
  - openjdk9

services:
  - docker

cache:
  directories:
  - $HOME/.m2

sudo: false # faster builds


addons:
  sonarcloud:
    organization: "abdotalaat"
    token:
      secure: $SONAR_TOKEN


script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=abdotalaat_vehicles-monitoring-app


after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t abdotalaat/config-service ./config-service
    - docker push abdotalaat/config-service
