language: java
jdk:
  - openjdk9

services:
  - docker

cache:
  directories:
  - $HOME/.m2

sudo: false # faster builds


addons:
  sonarcloud:
    organization: "abdotalaat"
    token:
      secure: $SONAR_TOKEN


script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=abdotalaat_vehicles-monitoring-app


after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t abdotalaat/config-service ./config-service
    - docker push abdotalaat/config-service
    - docker build -t abdotalaat/multi-nginx    ./nginx
    - docker push abdotalaat/multi-nginx
    - cd demo
    - mvn clean install
    - docker build -t abdotalaat/test-client    .
    - docker push abdotalaat/test-client
    - cd ..



deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "vehicles-monitoring-app"
  env: "VehiclesMonitoringApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-990019026330"
  bucket_path: "vehicles-monitoring-app"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure : "$AWS_SECRET_KEY"
