language: java
jdk:
- openjdk9

cache:
  directories:
  - $HOME/.m2

sudo: false # faster builds


addons:
  sonarcloud:
    organization: "abdotalaat"
    token:
      secure: $SONAR_TOKEN


script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=abdotalaat_vehicles-monitoring-app