version: '3.7'
services:

  config:
    build: ./config-service
    container_name: config
    image: abdotalaat/config
    restart: always
    ports:

      - 8081:8081

  discovery:
    build: ./discovery-service
    image: abdotalaat/discovery
    container_name: discovery
    restart: always
    ports:
      - 8761:8761

  api-gateway:
    build: ./gateway
    image: abdotalaat/gateway
    container_name: gateway
    restart: always
    ports:
    - 8080:8080
